Experiment No.11

Name : Pranav Menon\
Batch : ENTC - B1\
PRN.No : 25070123085

Aim of the experiment : Create Dataset and Load Dataset

In [7]:
# Dataset creation
import pandas as pd
data={
    "Roll_No": [101,102,103,104,105],
    "Gender" : ["Female","Male","Female","Male","Female"],
    "Department" : ["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA" : [8.2,7.5,9.1,6.8,8.7]
}
df = pd.DataFrame(data)
print(df)
df.to_csv("students.csv",index=False)
df

   Roll_No  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7

   Roll_No  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7

In [11]:
# To determine operations of Panda Library
print(df.shape)
print(df.size)
print(df.info())

(5, 4)
20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None

In [12]:
# To determine operations of Panda Library
print(df.describe())

          Roll_No     CGPA
count    5.000000  5.00000
mean   103.000000  8.06000
std      1.581139  0.92358
min    101.000000  6.80000
25%    102.000000  7.50000
50%    103.000000  8.20000
75%    104.000000  8.70000
max    105.000000  9.10000

In [19]:
# To Upload a Dataset
import pandas as pd
import numpy as np
df = pd.read_csv("/content/Cars93 csv.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [33]:
# To determine operations of Panda Library
print(df.size)
print(df.shape)

print(df.info())

print(df.describe())

print(df.head())

print(df.tail())


print(df.columns)


print(df.dtypes)

print(df.sample(5))


print(df.isnull().sum())


print(df.duplicated().sum())



print(df.nunique)

930
(93, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB
None
           Price   MPG.city  Horsepower  Passengers  Rear.seat.room  \
count  93.000000  93.000000   93.000000   93.000000       91.000000
mean   19.509677  22.365591  143.827957    5.086022       27.829670
std     9.659430   5.619812   52.374410    1.038979        2.989072
min     7.400000  15.000000   55.000000    2.000000       19.000000
25%    12.200000  18.000000  103.000000    4.000000       26.000000
50%    17.700000  21.000000  140.000000    5.000000       27.500000
75%    23.300000  25.000000  170.000000    6.000000       30.000000
max    61.900000  46.000000  300.000000    8.000000       36.000000

       Luggage.room
count     82.000000
mean      13.890244
std        2.997967
min        6.000000
25%       12.000000
50%       14.000000
75%       15.000000
max       22.000000
  Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0        Acura  Integra    Small   15.9        25                 NaN
1        Acura   Legend  Midsize   33.9        18  Driver & Passenger
2         Audi       90  Compact   29.1        20         Driver only
3         Audi      100  Midsize   37.7        19  Driver & Passenger
4          BMW     535i  Midsize   30.0        22         Driver only

   Horsepower  Passengers  Rear.seat.room  Luggage.room
0         140           5            26.5          11.0
1         200           5            30.0          15.0
2         172           5            28.0          14.0
3         172           6            31.0          17.0
4         208           4            27.0          13.0
   Manufacturer    Model     Type  Price  MPG.city             AirBags  \
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0
Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='object')
Manufacturer       object
Model              object
Type               object
Price             float64
MPG.city            int64
AirBags            object
Horsepower          int64
Passengers          int64
Rear.seat.room    float64
Luggage.room      float64
dtype: object
   Manufacturer       Model     Type  Price  MPG.city      AirBags  \
32         Ford       Tempo  Compact   11.3        22          NaN
15    Chevrolet  Lumina_APV      Van   16.3        18          NaN
30         Ford     Festiva    Small    7.4        31          NaN
71     Plymouth       Laser   Sporty   14.4        23          NaN
47     Infiniti         Q45  Midsize   47.9        17  Driver only

    Horsepower  Passengers  Rear.seat.room  Luggage.room
32          96           5            27.5          13.0
15         170           7            30.5           NaN
30          63           4            26.0          12.0
71          92           4            24.5           8.0
47         278           5            29.0          15.0
Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64
0
<bound method DataFrame.nunique of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]>